//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[__WWS__Connections] (
        ///    [ID]           BIGINT          NOT NULL,
        ///    [HostID]       BIGINT          DEFAULT ((0)) NOT NULL,
        ///    [TimestampUTC]    DATETIME        DEFAULT ((0)) NOT NULL,
        ///    [RequestedURI] NVARCHAR (2048) DEFAULT (&apos;&apos;) NOT NULL,
        ///    [Cookies]      NVARCHAR (2048) DEFAULT (&apos;&apos;) NOT NULL,
        ///    [HTTPMethod]   VARCHAR (16)    DEFAULT (&apos;GET&apos;) NOT NULL,
        ///    [StatusCode]   INT        NULL,
        ///    [RemotePort]   INT        DEFAULT (0xFFFE) NOT NULL,
        ///    PRIMARY KEY CLUSTERED [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo___WWS__Connections {
            get {
                return ResourceManager.GetString("dbo___WWS__Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[__WWS__IPData] (
        ///    [HostID]        BIGINT         NOT NULL,
        ///    [ISP]           NVARCHAR (256) DEFAULT (&apos;&apos;) NOT NULL,
        ///    [Organization]  NVARCHAR (256) DEFAULT (&apos;&apos;) NOT NULL,
        ///    [CountryCode]   VARCHAR (2)    DEFAULT (&apos;??&apos;) NOT NULL,
        ///    [Country]       VARCHAR (128)  DEFAULT (&apos;&apos;) NOT NULL,
        ///    [RegionCode]    VARCHAR (2)    DEFAULT (&apos;??&apos;) NOT NULL,
        ///    [Region]        VARCHAR (128)  DEFAULT (&apos;&apos;) NOT NULL,
        ///    [City]          NVARCHAR (128) DEFAULT (&apos;&apos;) NOT NULL,
        ///    [Latitu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo___WWS__IPData {
            get {
                return ResourceManager.GetString("dbo___WWS__IPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[__WWS__RemoteHosts] (
        ///    [ID]        BIGINT        NOT NULL,
        ///    [IPAddress] VARCHAR (64)  DEFAULT (&apos;[::]&apos;) NOT NULL,
        ///    [UserAgent] NVARCHAR (512) DEFAULT (&apos;&apos;) NOT NULL,
        ///    PRIMARY KEY CLUSTERED ([ID] ASC),
        ///    CONSTRAINT [RemoteHost] UNIQUE NONCLUSTERED ([IPAddress] ASC, [UserAgent] ASC)
        ///);
        ///
        ///.
        /// </summary>
        internal static string dbo___WWS__RemoteHosts {
            get {
                return ResourceManager.GetString("dbo___WWS__RemoteHosts", resourceCulture);
            }
        }
    }
}
